[package]
name = "combined_lib"
version = "3.48.0"
lean_version = "leanprover-community/lean:3.48.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "5c60b7e3dc353e1cd8262c8293d2d3c137bac3f6"}
